### ISSUE TITLE
Improve the Readme.md for a TO-DO list app.

### ISSUE THREAD

**Issue by zippytyro** [zippytyro/Turbodone-TODO-list-app#2]
### **Add more content relevant content in the readme file.**
- Add more screenshots, or uses of the app
- At the end mention your username as a contributor.

Live link - [here](https://turbodone.herokuapp.com/)

---------------------------------------------

### How to contribute
- Fork this repo
- clone it to your own machine 
- create a new branch naming it as your username
- Edit the required files
- Commit and push

After that make PR
Thanks

**Comment by rt1301** [comment]
Can I work on this issue, can you assign it to me?

**Comment by PriyanshTri** [comment]
I want to work on this. please assign this to me.

**Comment by rt1301** [comment]
I have made a PR regarding this issue, please give it a look

**Comment by zippytyro** [comment]
@PriyanshTri the issue has been solved.
